"""initial migration - create books table

Revision ID: 18325abf99f0
Revises: 
Create Date: 2025-10-10 07:54:37.180144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18325abf99f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('copies', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
